Repository pytest-dev/pytest, pull requests merged in 2019-08, with the labels that each got.

#5627 Handle only known functions in rm_rf
  src/_pytest/pathlib.py
  testing/test_tmpdir.py
Labels: type: bug, type: regression

#5697 Fix RuntimeError when trying to collect package with "__init__.py" only
  changelog/4344.bugfix.rst
  src/_pytest/main.py
  testing/test_collection.py
Labels: needs backport

#5056 Inject width via pylib to argparse formatter
  changelog/5056.trivial.rst
  src/_pytest/config/argparsing.py
  testing/test_config.py
Labels: type: enhancement

#5762 Docs: update tense
  doc/en/py27-py34-deprecation.rst
Labels: type: docs

#5673 1/X Fix check_untyped_defs = True mypy errors
  src/_pytest/_code/code.py
  src/_pytest/_code/source.py
  src/_pytest/assertion/__init__.py
  src/_pytest/assertion/rewrite.py
  src/_pytest/assertion/util.py
  src/_pytest/config/__init__.py
  src/_pytest/config/argparsing.py
  src/_pytest/config/findpaths.py
  src/_pytest/mark/evaluate.py
  src/_pytest/mark/structures.py
  src/_pytest/nodes.py
  src/_pytest/reports.py
  src/_pytest/runner.py
Labels: type: enhancement

#5808 Fix "lexer" being used when uploading to bpaste.net
  changelog/5806.bugfix.rst
  src/_pytest/pastebin.py
  testing/test_pastebin.py
Labels: needs backport
