Repository pytest-dev/pytest, pull requests merged in 2019-05, with the labels that each got.

#5211 Upgrade PyPy to 7.1.1
  .travis.yml
Labels: type: infrastructure

#5045 Skip test_source_mtime_long_long on 32bit and lower platforms
  testing/test_assertrewrite.py
Labels: status: needs information

#5013 Display message from reprcrash in short test summary
  changelog/5013.feature.rst
  changelog/5013.trivial.rst
  setup.py
  src/_pytest/skipping.py
  src/_pytest/terminal.py
  testing/acceptance_test.py
  testing/test_skipping.py
  testing/test_terminal.py
Labels: type: enhancement

#5091 Improve output of ini options in --help
  changelog/5091.feature.rst
  src/_pytest/helpconfig.py
Labels: type: enhancement
