Repository pytest-dev/pytest, pull requests merged in 2019-07, with the labels that each got.

#5479 Fix pytest.raises handling of unicode exceptions in Python 2
  changelog/5478.bugfix.rst
  src/_pytest/_code/code.py
  testing/python/raises.py
Labels: type: bug

#5555 Handle xfail(strict=True) properly in --step-wise mode
  changelog/5547.bugfix.rst
  src/_pytest/stepwise.py
  testing/test_stepwise.py
Labels: needs backport

#5560 Fix comment in stepwise (follow up to #5555) [skip ci]
  src/_pytest/stepwise.py
Labels: needs backport

#5588 Fix rmtree to remove directories with read-only files
  changelog/5524.bugfix.rst
  src/_pytest/cacheprovider.py
  src/_pytest/pathlib.py
  testing/test_tmpdir.py
Labels: needs backport

#5636 Fix ordering of sys modules snapshot
  testing/test_pytester.py
Labels: needs backport

#5650 Improve output when parsing an ini configuration fails
  changelog/5650.bugfix.rst
  src/_pytest/config/findpaths.py
  testing/test_config.py
Labels: needs backport

#5665 In test_xfail_handling, only remove __pycache__ if it exists
  changelog/5664.trivial.rst
  testing/test_stepwise.py
Labels: type: selftests
