Repository pytest-dev/pytest, pull requests merged in 2019-10, with the labels that each got.

#5902 Fix warnings with attrs 19.2 and fix object assertions
  src/_pytest/assertion/util.py
  src/_pytest/compat.py
  src/_pytest/mark/structures.py
  testing/test_assertion.py
Labels: needs backport

#5922 ci: test oldest supported attrs
  .travis.yml
  setup.py
  tox.ini
Labels: type: infrastructure

#6004 cache: NFPlugin: keep known nodeids
  changelog/5206.bugfix.rst
  src/_pytest/cacheprovider.py
  testing/test_cacheprovider.py
Labels: plugin: cache, type: bug

#5061 Multiple colors with terminal summary_stats
  changelog/5061.feature.rst
  src/_pytest/terminal.py
  testing/test_pdb.py
  testing/test_terminal.py
Labels: topic: reporting, type: enhancement

#6028 capture: improve message with DontReadFromInput's IOError
  src/_pytest/capture.py
Labels: plugin: capture, type: enhancement

#6044 Review rm_rf handling of FileNotFoundErrors
  changelog/6044.bugfix.rst
  src/_pytest/pathlib.py
  testing/test_tmpdir.py
Labels: needs backport
