Repository pytest-dev/pytest, pull requests merged in 2020-05, with the labels that each got.

#7143 Allow File.from_parent to forward custom parameters to the constructor
  changelog/7143.bugfix.rst
  src/_pytest/nodes.py
  testing/test_collection.py
Labels: needs backport

#7144 Let unittest frameworks deal with async functions
  .github/workflows/main.yml
  changelog/7110.bugfix.rst
  src/_pytest/compat.py
  src/_pytest/python.py
  src/_pytest/unittest.py
  testing/example_scripts/unittest/test_unittest_asyncio.py
  testing/example_scripts/unittest/test_unittest_asynctest.py
  testing/test_unittest.py
  tox.ini
Labels: needs backport

#7151 Fix cleanup functions not being invoked on test failures
  changelog/6947.bugfix.rst
  src/_pytest/debugging.py
  src/_pytest/unittest.py
  testing/test_unittest.py
Labels: needs backport

#7168 'saferepr' handles classes with broken __getattribute__
  changelog/7145.bugfix.rst
  src/_pytest/_io/saferepr.py
  testing/io/test_saferepr.py
Labels: needs backport

#7179 Fix tests for python3.9
  .github/workflows/main.yml
  setup.cfg
  testing/code/test_source.py
  tox.ini
Labels: needs backport

#7186 Fix _is_setup_py for files encoded differently than locale
  changelog/7180.bugfix.rst
  src/_pytest/doctest.py
  testing/test_doctest.py
Labels: needs backport

#7213 Make docs reflect that `yield`-based tests are now completely unsupported
  doc/en/nose.rst
Labels: type: docs

#7205 Issue 7126 - "saferepr" to avoid BytesWarning when using --setup-show
  AUTHORS
  changelog/7126.bugfix.rst
  src/_pytest/setuponly.py
  testing/test_setuponly.py
Labels: topic: reporting, type: bug

#6991 Fix regressions with --lf plugin
  changelog/6991.bugfix.rst
  changelog/6991.improvement.rst
  src/_pytest/cacheprovider.py
  src/_pytest/terminal.py
  testing/test_cacheprovider.py
Labels: needs backport

#6686 doc: highlight difference between progress percentage & code coverage
  doc/en/getting-started.rst
Labels: type: docs

#6817 Keep explicit newlines with help texts
  changelog/6817.improvement.rst
  src/_pytest/assertion/__init__.py
  src/_pytest/cacheprovider.py
  src/_pytest/config/argparsing.py
  src/_pytest/helpconfig.py
  src/_pytest/mark/__init__.py
  testing/test_helpconfig.py
Labels: type: enhancement

#7200 CONTRIBUTING: add section about backporting fixes to patch releases
  CONTRIBUTING.rst
Labels: type: docs

#7257 Prevent pytest from printing ConftestImportFailure traceback
  changelog/6956.bugfix.rst
  src/_pytest/nodes.py
  testing/python/collect.py
  testing/test_reports.py
Labels: needs backport

#7236 Do not call TestCase.tearDown for skipped tests
  changelog/7215.bugfix.rst
  src/_pytest/unittest.py
  testing/test_unittest.py
Labels: needs backport

#7220 Use abspath for errors when cwd changes during testing
  changelog/6428.bugfix.rst
  src/_pytest/nodes.py
  testing/test_nodes.py
Labels: needs backport
