Repository pytest-dev/pytest, pull requests merged in 2020-01, with the labels that each got.

#6407 Remove usage of parser module (deprecated in Python 3.9)
  changelog/6404.trivial.rst
  src/_pytest/_code/source.py
  testing/code/test_source.py
Labels: backported

#6621 Docs: Don't wrap the markdown for GitHub releases
  scripts/publish-gh-release-notes.py
Labels: type: enhancement, type: infrastructure

#6639 Fix favicon for Chrome and Opera
  doc/en/conf.py
  doc/en/img/favicon.png
  doc/en/img/pytest1favi.ico
Labels: type: docs
