Repository pytest-dev/pytest, pull requests merged in 2020-02, with the labels that each got.

#6661 DOC: it's called pytestmark, not pytest_mark
  doc/en/reference.rst
Labels: type: bug, type: docs

#6443 pluginmanager.consider_preparse: add exclude_only kwarg
  changelog/6443.breaking.rst
  src/_pytest/config/__init__.py
  testing/test_config.py
  testing/test_warnings.py
Labels: topic: config, type: enhancement

#6646 assertion: save/restore hooks on item
  changelog/6646.bugfix.rst
  src/_pytest/assertion/__init__.py
  src/_pytest/config/__init__.py
  testing/test_assertion.py
Labels: topic: rewrite, type: bug

#6660 Handle `Exit` exception in `pytest_sessionfinish`
  changelog/6660.bugfix.rst
  src/_pytest/main.py
  testing/test_main.py
Labels: type: bug

#6658 Use code highlighting if pygments is installed
  changelog/6658.improvement.rst
  src/_pytest/_code/code.py
  src/_pytest/_io/__init__.py
  testing/code/test_terminal_writer.py
  testing/conftest.py
  testing/test_terminal.py
  tox.ini
Labels: topic: reporting, type: enhancement

#6742 Expand first sentence on fixtures into a paragraph
  changelog/6742.doc.rst
  doc/en/fixture.rst
Labels: type: docs, type: enhancement

#6409 terminal: refactor, no yellow ("boring") for non-last item
  changelog/6409.bugfix.rst
  src/_pytest/terminal.py
  testing/test_terminal.py
Labels: topic: reporting, type: bug

#6669 doctest: handle any OutcomeException
  changelog/310.bugfix.rst
  src/_pytest/doctest.py
  testing/test_doctest.py
Labels: plugin: doctests, type: enhancement

#6696 doc: add list of fixtures to start of fixture chapter
  AUTHORS
  changelog/6696.doc.rst
  doc/en/cache.rst
  doc/en/changelog.rst
  doc/en/conf.py
  doc/en/fixture.rst
  doc/en/reference.rst
Labels: type: docs, type: enhancement

#6801 doctest: strip newlines with unexpected exceptions
  changelog/6801.bugfix.rst
  src/_pytest/doctest.py
  testing/test_doctest.py
Labels: plugin: doctests, type: bug

#6807 docs: fix reference to config.cache fixture
  doc/en/cache.rst
  doc/en/reference.rst
Labels: type: docs

#6808 docs: generate index and add it to globaltoc sidebar
  doc/en/_templates/globaltoc.html
  doc/en/conf.py
Labels: type: docs, type: enhancement

#6795 Improve UsageError with invalid `-o` style
  changelog/6795.improvement.rst
  src/_pytest/config/__init__.py
  testing/test_config.py
Labels: topic: config, type: enhancement

#6841 Add Read The Docs badge to README
  README.rst
Labels: type: docs
