Repository pytest-dev/pytest, pull requests merged in 2021-08, with the labels that each got.

#8804 logging: Make it possible to add cli colors to custom log levels
  AUTHORS
  changelog/8803.improvement.rst
  doc/en/how-to/logging.rst
  src/_pytest/logging.py
Labels: topic: reporting, plugin: logging

#9017 Docs: refer to non-deprecated unittest alias
  doc/en/how-to/assert.rst
Labels: type: docs

#9022 doc: Update trainings
  doc/en/index.rst
Labels: type: docs, topic: website, needs backport

#9053 As discussed in Discord, move 3.10 changelog to trivial
  changelog/8494.trivial.rst
Labels: needs backport
