Repository pytest-dev/pytest, pull requests merged in 2022-01, with the labels that each got.

#9400 Ensure Config.inifile is available during pytest_cmdline_main
  changelog/9396.bugfix.rst
  src/_pytest/legacypath.py
  testing/test_config.py
  testing/test_legacypath.py
Labels: needs backport, backport 7.0.x

#9464 Doc update: clarify -W syntax
  doc/en/how-to/capture-warnings.rst
Labels: needs backport

#9484 config: fix incorrect cache hit check in _getconftestmodules
  src/_pytest/config/__init__.py
Labels: needs backport

#9494 python: add back `instance` accessor to all python nodes, not just Function
  src/_pytest/python.py
  testing/test_collection.py
Labels: needs backport

#9506 Improve on configuration file docs section
  changelog/9505.trivial.rst
  doc/en/reference/customize.rst
Labels: backport 7.0.x

#9495 Add docs on pytest.warns(None) deprecation
  changelog/9404.doc.rst
  doc/en/deprecations.rst
  doc/en/how-to/capture-warnings.rst
  src/_pytest/deprecated.py
  testing/deprecated_test.py
Labels: needs backport

#9512 testing: avoid private pluggy attributes in test
  testing/test_config.py
Labels: needs backport

#9532 config: avoid stat storm in _getconftestmodules
  src/_pytest/config/__init__.py
Labels: needs backport

#9545 doc/reference: don't document `pytest.__version__` under "Marks"
  doc/en/reference/reference.rst
Labels: needs backport

#9498 Add additional docs for uncooperative ctor deprecation
  doc/en/deprecations.rst
  doc/en/example/nonpython/conftest.py
  src/_pytest/nodes.py
Labels: needs backport

#9475 Make 'warnings' and 'deselected' in assert_outcomes optional
  src/_pytest/pytester.py
  src/_pytest/pytester_assertions.py
  testing/test_pytester.py
Labels: needs backport

#9558 doc: Add ellipsis to warning usecase list
  doc/en/how-to/capture-warnings.rst
Labels: type: docs, needs backport

#9559 Add missing cooperative constructor changelog
  changelog/9488.deprecation.rst
Labels: needs backport

#9560 ci: Bump up timeout
  .github/workflows/main.yml
Labels: needs backport

#9561 doc: Recategorize 7.0.0 changelog items
  changelog/9505.doc.rst
  changelog/9521.trivial.rst
Labels: needs backport
