Repository pytest-dev/pytest, pull requests merged in 2022-10, with the labels that each got.

#9118 deprecate hook configuration via marks/attributes
  changelog/4562.deprecation.rst
  doc/en/deprecations.rst
  extra/setup-py.test/setup.py
  pyproject.toml
  src/_pytest/config/__init__.py
  src/_pytest/deprecated.py
  src/_pytest/warning_types.py
  testing/deprecated_test.py
  testing/plugins_integration/requirements.txt
Labels: type: deprecation

#10339 Fix a few broken links in the documentation.
  CONTRIBUTING.rst
  doc/en/changelog.rst
  doc/en/example/nonpython.rst
  src/_pytest/recwarn.py
Labels: needs backport

#10348 doc: Add second day for enterPy training
  doc/en/index.rst
Labels: needs backport

#10226 Use exceptiongroup for multiple errors during teardown
  changelog/10226.improvement.rst
  src/_pytest/runner.py
  testing/test_runner.py
Labels: type: refactoring

#10423 Edit changelog for 7.2.0
  doc/en/changelog.rst
Labels: needs backport
