Repository pytest-dev/pytest, pull requests merged in 2022-05, with the labels that each got.

#9875 Add colors to summary
  src/_pytest/terminal.py
  testing/test_skipping.py
  testing/test_terminal.py
Labels: type: enhancement

#10007 Do not advertise that importlib will be default import mode
  doc/en/explanation/goodpractices.rst
  doc/en/explanation/pythonpath.rst
Labels: needs backport

#9883 Document the --code-highlight default
  changelog/9883.improvement.rst
  doc/en/reference/reference.rst
  src/_pytest/assertion/__init__.py
  src/_pytest/cacheprovider.py
  src/_pytest/capture.py
  src/_pytest/config/__init__.py
  src/_pytest/config/argparsing.py
  src/_pytest/debugging.py
  src/_pytest/doctest.py
  src/_pytest/faulthandler.py
  src/_pytest/fixtures.py
  src/_pytest/helpconfig.py
  src/_pytest/junitxml.py
  src/_pytest/logging.py
  src/_pytest/main.py
  src/_pytest/mark/__init__.py
  src/_pytest/pastebin.py
  src/_pytest/pytester.py
  src/_pytest/python.py
  src/_pytest/runner.py
  src/_pytest/setuponly.py
  src/_pytest/setupplan.py
  src/_pytest/skipping.py
  src/_pytest/stepwise.py
  src/_pytest/terminal.py
  testing/test_config.py
  testing/test_helpconfig.py
  testing/test_stepwise.py
Labels: type: docs
