Repository pytest-dev/pytest, pull requests merged in 2022-04, with the labels that each got.

#9842 fix comparison of dataclasses with `InitVar`
  changelog/9820.bugfix.rst
  src/_pytest/assertion/util.py
  testing/example_scripts/dataclasses/test_compare_initvar.py
  testing/test_assertion.py
Labels: needs backport

#9854 Docs: link to easy issues in contributing guide
  CONTRIBUTING.rst
Labels: type: docs

#9878 Fix wrong `log_file` docs
  doc/en/how-to/logging.rst
  doc/en/reference/reference.rst
Labels: type: docs, plugin: logging, needs backport

#9900 doc: Reformat/Modernize some code
  doc/en/example/attic.rst
  doc/en/example/markers.rst
  doc/en/example/parametrize.rst
  doc/en/example/simple.rst
  doc/en/how-to/assert.rst
  doc/en/how-to/cache.rst
  doc/en/how-to/capture-warnings.rst
  doc/en/how-to/doctest.rst
  doc/en/how-to/fixtures.rst
  doc/en/how-to/logging.rst
  doc/en/how-to/skipping.rst
  doc/en/how-to/unittest.rst
  doc/en/how-to/usage.rst
  doc/en/how-to/writing_hook_functions.rst
  doc/en/how-to/writing_plugins.rst
  doc/en/how-to/xunit_setup.rst
Labels: type: docs
