Repository pytest-dev/pytest, pull requests merged in 2023-07, with the labels that each got.

#11155 fix #10447 - consider marks in reverse mro order to give base classes priority
  changelog/10447.bugfix.rst
  src/_pytest/mark/structures.py
  testing/test_mark.py
Labels: needs backport, backport 7.3.x

#10925 switch to deploy environment and configure for pypi oidc
  .github/workflows/deploy.yml
Labels: backport 7.3.x

#11171 Update open trainings
  doc/en/index.rst
Labels: type: docs, needs backport
