Repository pytest-dev/pytest, pull requests merged in 2024-06, with the labels that each got.

#12486 🔥 Exterminate legacy backport GHA workflow
  .github/workflows/backport.yml
  AUTHORS
Labels: skip news

#12488 🧪 Make required CI jobs match branch protection
  .github/workflows/test.yml
Labels: backport 8.2.x, skip news

#12494 📝 Rename the RTD config to canonical filename
  .readthedocs.yaml
Labels: skip news

#12493 📝💅 Always render changelog draft @ Sphinx docs
  .gitignore
  .readthedocs.yaml
  doc/en/changelog.rst
  doc/en/conf.py
  doc/en/requirements.txt
  scripts/towncrier-draft-to-file.py
  tox.ini
Labels: backport 8.2.x, skip news

#12469 📝 Make "setuptools entrypoint" term generic
  changelog/12469.doc.rst
  changelog/12469.improvement.rst
  doc/en/example/simple.rst
  doc/en/how-to/fixtures.rst
  doc/en/how-to/usage.rst
  doc/en/how-to/writing_plugins.rst
  doc/en/reference/customize.rst
  doc/en/reference/reference.rst
  src/_pytest/config/__init__.py
  src/_pytest/helpconfig.py
  testing/test_assertion.py
  testing/test_helpconfig.py
Labels: bot:chronographer:provided

#12503 🚑🧪📝 Allow invoking git in tox
  tox.ini
Labels: skip news

#12501 📝💅 Split trivial change log category into 3
  .pre-commit-config.yaml
  changelog/.gitignore
  changelog/12501.contrib.rst
  changelog/README.rst
  pyproject.toml
Labels: backport 8.2.x, bot:chronographer:provided

#12498 🎨 Add descriptions to all `tox` environments
  changelog/12498.contrib.rst
  tox.ini
Labels: bot:chronographer:provided

#12507 📝 Add a change note for PR #12493
  changelog/12493.contrib.rst
Labels: bot:chronographer:provided

#12506 [PR #12501/b08b6d1 backport][8.2.x] 📝💅 Split trivial change log category into 3
  .pre-commit-config.yaml
  changelog/.gitignore
  changelog/12501.contrib.rst
  changelog/README.rst
  pyproject.toml
Labels: bot:chronographer:provided

#12502 🧪 Make a draft based plugin bump PR CI trigger
  .github/workflows/test.yml
  .github/workflows/update-plugin-list.yml
  changelog/12502.contrib.rst
Labels: bot:chronographer:provided

#12508 🧪🚑 Pass a Codecov config to the action @ GHA
  .github/workflows/test.yml
  codecov.yml
Labels: backport 8.2.x, skip news

#12492 refactor: simplify bound method representation
  AUTHORS
  changelog/389.improvement.rst
  src/_pytest/_io/saferepr.py
  src/_pytest/assertion/rewrite.py
  testing/test_assertrewrite.py
Labels: bot:chronographer:provided

#12500 feat: support keyword arguments in marker expressions
  AUTHORS
  changelog/12281.feature.rst
  doc/en/example/markers.rst
  doc/en/how-to/usage.rst
  pyproject.toml
  src/_pytest/mark/__init__.py
  src/_pytest/mark/expression.py
  testing/test_mark.py
  testing/test_mark_expression.py
Labels: bot:chronographer:provided

#12455 Update `contact.rst`: Update Matrix link
  doc/en/contact.rst
Labels: backport 8.2.x, skip news

#12517 🧪 Bump the `alls-green` action to 223erbb7
  .github/workflows/test.yml
Labels: backport 8.2.x, skip news

#12516 🚑🧪 Set the Codecov token directly in GHA
  .github/workflows/test.yml
Labels: backport 8.2.x, skip news

#12522 📝 Replace GH/PyPI `extlinks` w/ `sphinx-issues`
  changelog/12522.contrib.rst
  doc/en/announce/release-2.9.0.rst
  doc/en/announce/release-2.9.1.rst
  doc/en/announce/release-2.9.2.rst
  doc/en/changelog.rst
  doc/en/conf.py
  doc/en/historical-notes.rst
  doc/en/requirements.txt
Labels: backport 8.2.x, bot:chronographer:provided

#12514 Update trainings
  doc/en/index.rst
Labels: type: docs, backport 8.2.x, skip news

#12523 Improve documentation & other kinks of marker keyword expression PR #12500
  doc/en/example/markers.rst
  doc/en/how-to/usage.rst
  src/_pytest/mark/expression.py
  testing/test_mark.py
  testing/test_mark_expression.py
Labels: skip news

#12491 [junitxml] add timezone to testsuite timestamp
  AUTHORS
  changelog/7662.improvement.rst
  src/_pytest/junitxml.py
  testing/test_junitxml.py
Labels: bot:chronographer:provided

#12545 Support venv detection on Windows with mingw Python
  AUTHORS
  changelog/12544.improvement.rst
  doc/en/reference/reference.rst
  src/_pytest/main.py
  testing/test_collection.py
Labels: bot:chronographer:provided
