Repository pytest-dev/pytest, pull requests merged in 2024-11, with the labels that each got.

#12942 Rename changelog entries to breaking
  changelog/11372.breaking.rst
  changelog/12346.breaking.rst
Labels: skip news

#12954 [pylint consider-using-any-or-all] Fix or disable all detected issues
  pyproject.toml
  src/_pytest/mark/__init__.py
Labels: skip news

#12962 add assertion to FixtureLookupError.formatrepr
  src/_pytest/fixtures.py
Labels: type: refactoring, skip news

#12967 Clarify docs on specifying multiple filters with pytest.mark.filterwarnings
  changelog/12966.doc.rst
  doc/en/how-to/capture-warnings.rst
Labels: bot:chronographer:provided, backport 8.3.x

#12930 DeprecationWarning if sync test requests async fixture
  changelog/10839.deprecation.rst
  doc/en/deprecations.rst
  pyproject.toml
  src/_pytest/fixtures.py
  testing/acceptance_test.py
Labels: bot:chronographer:provided

#12535 examples: be more precise about TestReport outcome
  changelog/12535.doc.rst
  doc/en/example/simple.rst
Labels: bot:chronographer:provided

#12968 Remove _pytest.compat.is_generator() fixes #12960
  changelog/12960.breaking.rst
  doc/en/deprecations.rst
  src/_pytest/compat.py
  src/_pytest/fixtures.py
  src/_pytest/python.py
  testing/test_collection.py
  testing/test_compat.py
  testing/test_terminal.py
Labels: bot:chronographer:provided

#12982 prevent Config.add_cleanup callbacks preventing other cleanups running
  changelog/12981.bugfix.rst
  src/_pytest/config/__init__.py
  testing/test_config.py
Labels: bot:chronographer:provided

#12959 Fix ANSI escape codes for colored output not handled correctly with pytest.fail(..., pytrace=False)
  AUTHORS
  changelog/12849.bugfix.rst
  src/_pytest/_code/code.py
  testing/code/test_excinfo.py
  testing/conftest.py
Labels: bot:chronographer:provided, backport 8.3.x

#12985 docs: Fix wrong statement about sys.modules with importlib import mode
  doc/en/explanation/goodpractices.rst
Labels: type: docs, skip news, backport 8.3.x

#12975 display single contained exception in excgroups in test summary
  changelog/12943.improvement.rst
  src/_pytest/_code/code.py
  testing/code/test_excinfo.py
Labels: bot:chronographer:provided

#9354 Use exact comparison for bool in approx()
  changelog/9353.bugfix.rst
  src/_pytest/python_api.py
  testing/python/approx.py
Labels: bot:chronographer:provided, backport 8.3.x

#13012 Fix 13010 - Ensure pytest.approx in sequence/collections only process instances of Number
  changelog/13010.improvement.rst
  src/_pytest/python_api.py
  testing/python/approx.py
Labels: bot:chronographer:provided

#13009 Upgrade ruff to 0.8.1 and fix existing issues
  .pre-commit-config.yaml
  bench/empty.py
  src/_pytest/_code/__init__.py
  src/_pytest/_code/code.py
  src/_pytest/_io/pprint.py
  src/_pytest/_py/error.py
  src/_pytest/assertion/rewrite.py
  src/_pytest/assertion/util.py
  src/_pytest/cacheprovider.py
  src/_pytest/capture.py
  src/_pytest/compat.py
  src/_pytest/doctest.py
  src/_pytest/fixtures.py
  src/_pytest/main.py
  src/_pytest/mark/expression.py
  src/_pytest/mark/structures.py
  src/_pytest/nodes.py
  src/_pytest/pytester.py
  src/_pytest/python.py
  src/_pytest/runner.py
  src/_pytest/skipping.py
  src/_pytest/terminal.py
  src/pytest/__init__.py
  testing/_py/test_local.py
  testing/example_scripts/dataclasses/test_compare_dataclasses_with_custom_eq.py
  testing/python/metafunc.py
  testing/test_assertion.py
  testing/test_conftest.py
  testing/test_doctest.py
  testing/test_terminal.py
Labels: dependencies, skip news

#12958 unraisablehook enhancements
  changelog/12958.improvement.rst
  src/_pytest/tracemalloc.py
  src/_pytest/unraisableexception.py
  src/_pytest/warnings.py
  testing/test_unraisableexception.py
Labels: bot:chronographer:provided
