Repository pytest-dev/pytest, pull requests merged in 2024-12, with the labels that each got.

#13008 Fix `pytest.mark.usefixtures()` without arguments silently erroring
  AUTHORS
  changelog/12426.improvement.rst
  src/_pytest/fixtures.py
  testing/plugins_integration/pytest.ini
  testing/python/fixtures.py
Labels: bot:chronographer:provided

#13019 Remove 'pip' command hint from release announcement
  RELEASING.rst
  scripts/release.patch.rst
Labels: skip news, backport 8.3.x

#12810 Add `discover_imports` in conf, don't collect imported classes named Test* closes #12749`
  AUTHORS
  changelog/12749.feature.rst
  doc/en/reference/reference.rst
  src/_pytest/main.py
  src/_pytest/python.py
  testing/test_collect_imported_tests.py
Labels: bot:chronographer:provided

#13016 threadexception enhancements
  changelog/13016.improvement.rst
  src/_pytest/threadexception.py
  src/_pytest/unraisableexception.py
  testing/test_threadexception.py
  testing/test_unraisableexception.py
Labels: bot:chronographer:provided

#13027 remove 1-second join from threadexception plugin
  changelog/13016.improvement.rst
  src/_pytest/threadexception.py
  testing/test_threadexception.py
Labels: skip news, bot:chronographer:provided

#13034 Wrong Comment in .git-blame-ignore-revs (closes #13033)
  .git-blame-ignore-revs
  AUTHORS
Labels: skip news

#12473 (fixtures): Replace fixture represenation with a class
  AUTHORS
  changelog/11525.improvement.rst
  doc/en/conf.py
  src/_pytest/assertion/rewrite.py
  src/_pytest/compat.py
  src/_pytest/fixtures.py
  testing/code/test_source.py
  testing/python/fixtures.py
  testing/test_assertrewrite.py
  testing/test_collection.py
  testing/test_compat.py
Labels: bot:chronographer:provided

#13029 fix `AttributeError` crash when using `--import-mode=importlib`
  changelog/13026.bugfix.rst
  src/_pytest/pathlib.py
  testing/test_pathlib.py
Labels: bot:chronographer:provided, backport 8.3.x

#13022 Fix parametrized mark over staticmethod decorator
  AUTHORS
  changelog/12863.bugfix.rst
  pyproject.toml
  src/_pytest/mark/structures.py
  testing/test_mark.py
Labels: bot:chronographer:provided

#13062 ci: harden github actions according to "zizmor" recommendations
  .github/workflows/deploy.yml
  .github/workflows/prepare-release-pr.yml
  .github/workflows/update-plugin-list.yml
Labels: skip news, backport 8.3.x

#13068 [8.3.x] ci: fix failing jobs due to pluggy requiring Python>=3.9
  .github/workflows/test.yml
Labels: skip news

#13069 pre-commit: add zizmor hook
  .pre-commit-config.yaml
Labels: skip news, backport 8.3.x

#13073 fix #13031: use the concrete id NOTSET for the empty parameter list
  changelog/13031.improvement.rst
  src/_pytest/mark/structures.py
  testing/test_mark.py
Labels: bot:chronographer:provided, backport 8.3.x
