Repository pytest-dev/pytest, pull requests merged in 2024-07, with the labels that each got.

#12531 🧪 Unmeasure coverage in tests expected to fail
  .coveragerc
  changelog/12531.contrib.rst
Labels: type: selftests, backport 8.2.x, bot:chronographer:provided

#12472 testresult: correctly apply verbose word markup and avoid crash
  changelog/12472.bugfix.rst
  src/_pytest/reports.py
  src/_pytest/terminal.py
  testing/test_terminal.py
Labels: bot:chronographer:provided

#12553 Revert "🚑🧪 Set the Codecov token directly in GHA"
  .github/workflows/test.yml
Labels: backport 8.2.x, skip news

#12559 📝 Add markup to the PR #12545 changelog entry
  changelog/12544.improvement.rst
  changelog/12545.improvement.rst
Labels: skip news

#12560 Correct the `:user:` role @ PR #12531 change note
  changelog/12531.contrib.rst
Labels: backport 8.2.x, skip news

#12562 🧪 Lint for typos in `:user:` RST role
  .pre-commit-config.yaml
  changelog/12562.contrib.rst
Labels: backport 8.2.x, bot:chronographer:provided

#12526 Fixed handling of invalid regex pattern
  AUTHORS
  changelog/12505.bugfix.rst
  src/_pytest/python_api.py
  testing/python/raises.py
Labels: bot:chronographer:provided

#12561 📝💄 Drop trailing period from #12502 byline
  changelog/12502.contrib.rst
Labels: skip news

#12563 📝🚑 Polish the PR #12264 changelog entry
  changelog/12204.bugfix.rst
  changelog/12264.bugfix.rst
Labels: skip news

#12574 [python 3.13] Mark functool.partial test to be skipped
  testing/python/fixtures.py
Labels: skip news

#12567 feat: add --fold-skipped=yes|no cli option
  changelog/12567.feature.rst
  doc/en/how-to/output.rst
  src/_pytest/terminal.py
  testing/test_terminal.py
Labels: bot:chronographer:provided

#12579 Cache class: Fix crash on data race on Windows.
  AUTHORS
  changelog/12580.bugfix.rst
  src/_pytest/cacheprovider.py
Labels: bot:chronographer:provided

#12578 details impact of specifying CI or BUILD_NUMBER
  changelog/12577.doc.rst
  doc/en/explanation/ci.rst
  doc/en/explanation/index.rst
  doc/en/reference/reference.rst
  src/_pytest/helpconfig.py
Labels: backport 8.2.x, bot:chronographer:provided

#12586 Fix heading level on index.rst
  doc/en/index.rst
Labels: backport 8.2.x, skip news

#12589 Remove done Europython training
  doc/en/index.rst
Labels: type: docs, backport 8.2.x, skip news

#12515 Update contact channels
  doc/en/contact.rst
Labels: type: docs, backport 8.2.x, skip news

#12623 doc: mention `PYTEST_DISABLE_PLUGIN_AUTOLOAD` in writing_plugins.rst
  doc/en/how-to/writing_plugins.rst
Labels: skip news

#12622 [pylint/ruff] Activate PLR / PLC messages in ruff
  pyproject.toml
  src/_pytest/_io/saferepr.py
  src/_pytest/helpconfig.py
Labels: skip news

#12600 fix: improved caching of parameterized fixtures
  AUTHORS
  changelog/6962.bugfix.rst
  src/_pytest/fixtures.py
  testing/python/fixtures.py
Labels: bot:chronographer:provided

#12557 Bump PyPy runtime to v3.9 @ GHA
  .github/workflows/test.yml
  changelog/11771.contrib.rst
  changelog/12557.contrib.rst
  testing/test_skipping.py
Labels: backport 8.2.x, bot:chronographer:provided

#12636 [8.3.x] doc/changelog: update 8.3.0 notes
  doc/en/changelog.rst
Labels: skip news

#12640 doc/changelog: update user tag
  doc/en/changelog.rst
Labels: skip news, backport 8.3.x

#12656 explicitly detect conda envs - fixes #12652
  changelog/12652.bugfix.rst
  src/_pytest/main.py
  testing/test_collection.py
Labels: bot:chronographer:provided, backport 8.3.x

#12661 Include TerminalReporter in reference docs #6649
  changelog/6649.doc.rst
  changelog/6649.misc.rst
  doc/en/reference/reference.rst
  src/_pytest/terminal.py
  src/pytest/__init__.py
Labels: bot:chronographer:provided
