Repository pytest-dev/pytest, pull requests merged in 2024-09, with the labels that each got.

#12772 doc: Remove past training
  doc/en/index.rst
Labels: type: docs, skip news, backport 8.3.x

#12769 Fix typos discovered by codespell
  .pre-commit-config.yaml
  AUTHORS
  CONTRIBUTING.rst
  changelog/12769.misc.rst
  doc/en/announce/release-2.3.0.rst
  doc/en/changelog.rst
  doc/en/deprecations.rst
  doc/en/explanation/fixtures.rst
  doc/en/funcarg_compare.rst
  doc/en/how-to/fixtures.rst
  doc/en/how-to/unittest.rst
  pyproject.toml
  src/_pytest/config/__init__.py
  src/_pytest/debugging.py
  testing/python/fixtures.py
  testing/test_config.py
Labels: bot:chronographer:provided, backport 8.3.x

#12706 Fix for Verbose mode not having default value on getoption call works on issue #9422
  changelog/9422.bugfix.rst
  doc/en/example/simple.rst
  src/_pytest/cacheprovider.py
  src/_pytest/config/__init__.py
  src/_pytest/fixtures.py
  src/_pytest/logging.py
  src/_pytest/nodes.py
  src/_pytest/python.py
  src/_pytest/runner.py
  src/_pytest/stepwise.py
  testing/acceptance_test.py
Labels: bot:chronographer:provided, backport 8.3.x

#12784 [doc] Fix minor typo in example/parametrize.rst
  doc/en/example/parametrize.rst
Labels: skip news, backport 8.3.x

#12708 Exception chains can be navigated when dropped into Pdb in Python 3.13+
  AUTHORS
  changelog/12707.improvement.rst
  src/_pytest/debugging.py
  testing/test_debugging.py
Labels: bot:chronographer:provided

#12760 Fix issue with slashes being turned into backslashes on Windows
  AUTHORS
  changelog/12745.bugfix.rst
  src/_pytest/config/__init__.py
  testing/test_terminal.py
Labels: bot:chronographer:provided, backport 8.3.x

#12781 do not discover properties when iterating fixtures
  changelog/12446.bugfix.rst
  src/_pytest/fixtures.py
  testing/python/collect.py
Labels: bot:chronographer:provided, backport 8.3.x

#12795 Include co-authors in release announcement
  scripts/release.py
Labels: skip news

#12826 Added mention of Databricks fixture plugin for PyTest
  scripts/update-plugin-list.py
Labels: skip news, backport 8.3.x

#12766 Implement CLI options to set truncation thresholds
  AUTHORS
  changelog/12765.feature.rst
  doc/en/how-to/output.rst
  doc/en/reference/reference.rst
  src/_pytest/assertion/__init__.py
  src/_pytest/assertion/truncate.py
  testing/test_assertion.py
Labels: bot:chronographer:provided

#12829 Remove missing msg parameter from docs
  doc/en/reference/reference.rst
Labels: type: docs, skip news, backport 8.3.x

#12840 Clarify that `capfdbinary` captures on a filedescriptor level.
  doc/en/how-to/capture-stdout-stderr.rst
Labels: skip news, bot:chronographer:provided, backport 8.3.x

#12752 Fixed the issue of causes ``KeyError`` when using the parameter ``--import-mode=importlib`` in pytest>=8.2 . (#12592)
  changelog/12592.bugfix.rst
  src/_pytest/pathlib.py
  testing/test_pathlib.py
Labels: bot:chronographer:provided
