Repository pytest-dev/pytest, pull requests merged in 2024-01, with the labels that each got.

#11760 terminalwriter: fix crash trying to highlight empty source
  changelog/11758.bugfix.rst
  src/_pytest/_io/terminalwriter.py
  testing/io/test_terminalwriter.py
Labels: needs backport

#11754 Improve GitHub release workflow
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
  scripts/.gitignore
  scripts/generate-gh-release-notes.py
  scripts/prepare-release-pr.py
  scripts/release.py
  scripts/towncrier-draft-to-file.py
  scripts/update-plugin-list.py
  tox.ini
Labels: needs backport

#11767 Update docstring of scripts/generate-gh-release-notes.py
  scripts/generate-gh-release-notes.py
Labels: needs backport

#11819 doc: Update training dates and add pytest sprint
  doc/en/index.rst
Labels: type: docs, needs backport

#11823 doc: Remove sold out training
  doc/en/index.rst
Labels: type: docs, needs backport

#11839 Properly attach packages to the GH release notes
  .github/workflows/deploy.yml
Labels: backport 8.0.x

#11861 fix: avoid rounding microsecond to `1_000_000`
  changelog/11861.bugfix.rst
  src/_pytest/logging.py
Labels: needs backport

#11892 fix incorrect examples for group_contains
  doc/en/how-to/assert.rst
Labels: needs backport
