Repository pytest-dev/pytest, pull requests merged in 2024-10, with the labels that each got.

#12815 preserve source positions for assertion rewriting
  AUTHORS
  changelog/12818.bugfix.rst
  src/_pytest/assertion/rewrite.py
  testing/test_assertrewrite.py
Labels: bot:chronographer:provided

#12828 Prohibit pytest.mark.usefixtures in pytest.param
  AUTHORS
  changelog/4112.improvement.rst
  src/_pytest/mark/__init__.py
  src/_pytest/mark/structures.py
  testing/python/integration.py
Labels: bot:chronographer:provided

#12861 Fix `disable_test_id_escaping_and_forfeit_all_rights_to_community_support` option when using `pytest.param(..., id="...")`
  AUTHORS
  changelog/9037.bugfix.rst
  doc/en/reference/reference.rst
  src/_pytest/mark/structures.py
  src/_pytest/python.py
  testing/python/metafunc.py
Labels: bot:chronographer:provided

#12866 Docs: improve/cleanup reference from/to recwarn
  changelog/12866.doc.rst
  doc/en/builtin.rst
  doc/en/how-to/capture-warnings.rst
  doc/en/reference/reference.rst
  src/_pytest/recwarn.py
Labels: bot:chronographer:provided, backport 8.3.x

#12869 [pre-commit] Fix local pre-commit installation for python != 3.8
  .pre-commit-config.yaml
Labels: skip news, backport 8.3.x

#12872 [mypy] python-version independant from pre-commit
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip news, backport 8.3.x

#12885 Fix pdb selftests on Python 3.13
  .github/workflows/test.yml
  changelog/12497.contrib.rst
  testing/test_debugging.py
Labels: bot:chronographer:provided, backport 8.3.x

#12886 Improve pytest.Config.getoption docstring
  AUTHORS
  changelog/10558.doc.rst
  src/_pytest/config/__init__.py
  testing/test_config.py
Labels: bot:chronographer:provided, backport 8.3.x

#12913 [minor] avoid test failing if the working path contains the string 'error'
  testing/python/fixtures.py
Labels: skip news

#12346 make async tests and tests that return non-None fail instead of warn
  changelog/11372.improvement.rst
  changelog/12346.misc.rst
  doc/en/changelog.rst
  doc/en/deprecations.rst
  doc/en/reference/reference.rst
  src/_pytest/python.py
  src/_pytest/warning_types.py
  src/pytest/__init__.py
  testing/acceptance_test.py
Labels: bot:chronographer:provided

#12912 Improve docs on basetemp and retention
  changelog/10829.doc.rst
  doc/en/how-to/tmp_path.rst
  doc/en/reference/reference.rst
  src/_pytest/legacypath.py
  src/_pytest/tmpdir.py
Labels: bot:chronographer:provided
