Repository pytest-dev/pytest, pull requests merged in 2024-08, with the labels that each got.

#12675 Pin towncrier due to incompatibility with sphinxcontrib-towncrier
  doc/en/broken-dep-constraints.txt
  doc/en/requirements.txt
Labels: skip news, backport 8.3.x

#12665 Improve approx scalar repr method for better readability
  changelog/6985.improvement.rst
  src/_pytest/python_api.py
  testing/python/approx.py
Labels: bot:chronographer:provided

#12679 Remove quotes from example tmp_path_retention_policy
  AUTHORS
  changelog/12678.doc.rst
  doc/en/reference/reference.rst
Labels: bot:chronographer:provided, backport 8.3.x

#12655 Revert "doc: Add changing RTD version to checklist"
  RELEASING.rst
Labels: skip news

#12662 Obey verbosity level when printing 'msg' part of assertions
  changelog/6682.bugfix.rst
  src/_pytest/assertion/rewrite.py
  testing/test_assertrewrite.py
Labels: bot:chronographer:provided, backport 8.3.x

#12672 Add merge/squash guidelines to CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: skip news, backport 8.3.x

#12536 Load plugins from paths in 'pythonpath' option
  changelog/11118.improvement.rst
  doc/en/reference/reference.rst
  src/_pytest/config/__init__.py
  src/_pytest/python_path.py
  testing/test_config.py
  testing/test_python_path.py
Labels: bot:chronographer:provided

#12694 Add Pierre to official contacts
  doc/en/contact.rst
Labels: skip news, backport 8.3.x

#12701 docs: Revise `cache_dir` option section
  doc/en/reference/reference.rst
Labels: skip news, backport 8.3.x

#12700 Fix `mypy` error in `errisinstance`
  changelog/12667.bugfix.rst
  src/_pytest/_code/code.py
Labels: bot:chronographer:provided, backport 8.3.x

#12542 Revert the unintended change in tests reordering from #11220
  changelog/12008.bugfix.rst
  src/_pytest/python.py
  testing/example_scripts/issue_519.py
  testing/python/metafunc.py
Labels: bot:chronographer:provided

#12729 docs: clarify `pytest_deselected`/`pytest_collection_modifyitems` usage
  changelog/12663.doc.rst
  src/_pytest/hookspec.py
Labels: bot:chronographer:provided, backport 8.3.x

#12743 MAINT: adding back Python 3.13 classifier
  pyproject.toml
Labels: skip news

#12744 Replaced `typing.Self` with `typing_extensions.Self`
  changelog/12744.bugfix.rst
  src/_pytest/doctest.py
  src/_pytest/nodes.py
  src/_pytest/python.py
Labels: bot:chronographer:provided, backport 8.3.x

#12747 Use oldest supported Python in mypy pre-commit checks
  .pre-commit-config.yaml
  src/_pytest/main.py
  src/_pytest/runner.py
  testing/test_runner.py
Labels: skip news, backport 8.3.x

#12716 Fix: pytest >=8.1.0 displays no diff for AssertionError with `--impor…
  AUTHORS
  changelog/12659.bugfix.rst
  src/_pytest/assertion/rewrite.py
  src/_pytest/pathlib.py
  testing/test_pathlib.py
Labels: bot:chronographer:provided, backport 8.3.x
