Repository pytest-dev/pytest, pull requests merged in 2025-03, with the labels that each got.

#13229 Allow hiding a parameter set from test name
  AUTHORS
  changelog/13228.feature.rst
  doc/en/reference/reference.rst
  src/_pytest/mark/__init__.py
  src/_pytest/mark/structures.py
  src/_pytest/python.py
  src/pytest/__init__.py
  testing/python/metafunc.py
  testing/test_mark.py
Labels: bot:chronographer:provided

#13256 📦📝 Allow modern Towncrier in docs builds
  changelog/13256.contrib.rst
  doc/en/broken-dep-constraints.txt
Labels: bot:chronographer:provided, backport 8.3.x

#13250 Add more resources and studies to flaky tests page in docs
  doc/en/explanation/flaky.rst
Labels: type: docs, skip news, backport 8.3.x

#12947 Copy docstrings to wrapped pdb methods
  changelog/12946.bugfix.rst
  src/_pytest/debugging.py
  testing/test_debugging.py
Labels: bot:chronographer:provided

#12854 Add capteesys capture fixture to bubble up output to `--capture` handler
  AUTHORS
  changelog/12081.feature.rst
  doc/en/how-to/capture-stdout-stderr.rst
  doc/en/reference/fixtures.rst
  doc/en/reference/reference.rst
  src/_pytest/capture.py
  testing/test_capture.py
Labels: bot:chronographer:provided

#12963 Added dedicated page about using types with pytest #12842
  AUTHORS
  changelog/12842.doc.rst
  doc/en/explanation/index.rst
  doc/en/explanation/types.rst
Labels: bot:chronographer:provided, backport 8.3.x

#13253 add --disable-plugin-autoload
  changelog/13253.feature.rst
  doc/en/how-to/plugins.rst
  doc/en/reference/reference.rst
  src/_pytest/config/__init__.py
  src/_pytest/helpconfig.py
  testing/test_assertion.py
  testing/test_config.py
Labels: bot:chronographer:provided

#13267 chore(changelog) Minor typo fix
  doc/en/changelog.rst
Labels: skip news

#13192 add RaisesGroup & Matcher
  changelog/11538.feature.rst
  changelog/12504.feature.rst
  doc/en/conf.py
  doc/en/getting-started.rst
  doc/en/how-to/assert.rst
  doc/en/reference/reference.rst
  src/_pytest/_code/code.py
  src/_pytest/mark/structures.py
  src/_pytest/outcomes.py
  src/_pytest/python_api.py
  src/_pytest/raises_group.py
  src/_pytest/skipping.py
  src/pytest/__init__.py
  testing/code/test_excinfo.py
  testing/python/raises.py
  testing/python/raises_group.py
  testing/typing_raises_group.py
Labels: bot:chronographer:provided

#13273 require codecov patch % to be 100%
  codecov.yml
Labels: skip news

#13275 improve raisesgroup code coverage
  src/_pytest/_code/code.py
  src/_pytest/raises_group.py
  testing/python/raises.py
  testing/python/raises_group.py
Labels: skip news

#13280 doc: Update trainings
  doc/en/index.rst
Labels: type: docs, skip news, backport 8.3.x

#12017 assorted code updates and f string migrations
  changelog/12017.contrib.rst
  src/_pytest/setuponly.py
  src/_pytest/timing.py
  testing/conftest.py
  testing/python/fixtures.py
  testing/test_junitxml.py
  testing/test_skipping.py
Labels: bot:chronographer:provided

#13291 fix attrs==25.2.0 compatibility
  changelog/13291.bugfix.rst
  src/_pytest/assertion/util.py
Labels: bot:chronographer:provided, backport 8.3.x

#13263 Fix prepare-release-pr script
  .github/workflows/prepare-release-pr.yml
  RELEASING.rst
  scripts/prepare-release-pr.py
  tox.ini
Labels: skip news, backport 8.3.x

#13299 Update additional projects list to include my new plugin
  scripts/update-plugin-list.py
Labels: skip news

#13317 Specify minimum requirements for dependencies
  changelog/13317.packaging.rst
  pyproject.toml
Labels: bot:chronographer:provided

#13279 raisesgroup followups
  changelog/13192.feature.1.rst
  changelog/13192.feature.2.rst
  changelog/13192.feature.rst
  src/_pytest/mark/structures.py
  src/_pytest/python_api.py
  src/_pytest/raises.py
  src/_pytest/skipping.py
  src/pytest/__init__.py
  testing/code/test_excinfo.py
  testing/python/raises.py
  testing/python/raises_group.py
  testing/test_warning_types.py
  testing/typing_raises_group.py
Labels: bot:chronographer:provided
