Repository pytest-dev/pytest, pull requests merged in 2025-09, with the labels that each got.

#13682 Run Link Checks via scheduled workflow
  .github/workflows/doc-check-links.yml
  AUTHORS
  changelog/12474.contrib.rst
Labels: bot:chronographer:provided

#13684 Fix passenv CI in tox ini and make tests insensitive to the presence of the CI env variable
  changelog/13684.contrib.rst
  pyproject.toml
  testing/conftest.py
  testing/python/approx.py
  testing/test_faulthandler.py
  tox.ini
Labels: bot:chronographer:provided, backport 8.4.x

#13598 main: use a better windows short-path comparison method
  changelog/13598.bugfix.rst
  src/_pytest/main.py
  src/_pytest/pathlib.py
  testing/test_collection.py
Labels: bot:chronographer:provided

#13702 junitxml: do not print summary with `--quiet`
  changelog/13700.improvement.rst
  src/_pytest/junitxml.py
  testing/test_junitxml.py
Labels: bot:chronographer:provided

#13732 config: Do not fail if a warning filter category cannot be imported
  AUTHORS
  changelog/13732.improvement.rst
  src/_pytest/config/__init__.py
  testing/test_config.py
  testing/test_warnings.py
Labels: bot:chronographer:provided

#13761 [ruff configuration] Fix legacy alias and top-level linter settings
  .pre-commit-config.yaml
  doc/en/example/.ruff.toml
Labels: skip news
