Repository pytest-dev/pytest, pull requests merged in 2025-02, with the labels that each got.

#13176 Add readline workaround for libedit
  changelog/12888.bugfix.rst
  src/_pytest/capture.py
  testing/test_capture.py
Labels: bot:chronographer:provided

#13124 Fixed invalid regex handling in filterwarnings
  changelog/13119.bugfix.rst
  src/_pytest/config/__init__.py
  testing/test_warnings.py
Labels: bot:chronographer:provided

#13188 [8.3.x] Fix CI
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: skip news

#13196 doc: Change training to remote only
  doc/en/index.rst
Labels: skip news, backport 8.3.x

#13199 remove `git fetch` from tox docs environment
  tox.ini
Labels: skip news, backport 8.3.x

#13189 Make pygments mandatory and fix string highlighting
  changelog/13175.bugfix.rst
  changelog/7683.improvement.rst
  pyproject.toml
  src/_pytest/_io/terminalwriter.py
  src/_pytest/assertion/util.py
  testing/test_assertion.py
Labels: bot:chronographer:provided

#13215 Update capture-warnings.rst: Fix PEP number in link
  doc/en/how-to/capture-warnings.rst
Labels: skip news

#13222 doc: Clarify capturing .readouterr() return value
  doc/en/how-to/capture-stdout-stderr.rst
  doc/en/how-to/parametrize.rst
Labels: skip news, backport 8.3.x

#13193 Improvement for Parser.addini to facilite parsing of 'int' and 'float' values
  changelog/11381.improvement.rst
  src/_pytest/config/__init__.py
  src/_pytest/config/argparsing.py
  src/_pytest/config/findpaths.py
  testing/test_config.py
Labels: bot:chronographer:provided

#13221 Fix help sections for CLI options
  changelog/13221.doc.rst
  src/_pytest/capture.py
  src/_pytest/debugging.py
  src/_pytest/helpconfig.py
  src/_pytest/main.py
  src/_pytest/mark/__init__.py
  src/_pytest/pastebin.py
  src/_pytest/terminal.py
Labels: bot:chronographer:provided, backport 8.3.x
