Repository pytest-dev/pytest, pull requests merged in 2025-04, with the labels that each got.

#13339 Enable GitHub Sponsors and thanks.dev in FUNDING.yml
  .github/FUNDING.yml
Labels: skip news, backport 8.3.x

#13338 Fix broken ``approx`` when mixing numpy booleans and booleans
  AUTHORS
  changelog/13047.bugfix.rst
  src/_pytest/python_api.py
  testing/python/approx.py
Labels: bot:chronographer:provided, backport 8.3.x

#13343 Add title and change spelling for use of approx with non-numerics
  src/_pytest/python_api.py
  testing/python/approx.py
Labels: skip news, backport 8.3.x

#13345 Fix type hints for `TestReport.when` and `TestReport.location`
  changelog/13345.bugfix.rst
  src/_pytest/reports.py
Labels: bot:chronographer:provided

#13348 Clean up type hints from #13345 and add a test
  src/_pytest/reports.py
  testing/typing_checks.py
Labels: skip news, bot:chronographer:provided

#13346 Add note on using mixin classes for abstract test classes in documentation
  changelog/8612.doc.rst
  doc/en/example/pythoncollection.rst
Labels: bot:chronographer:provided, backport 8.3.x

#13318 Bugfix for pytest plugins set to hypothesis pytestplugin (#12647)
  changelog/12647.contrib.rst
  testing/test_helpconfig.py
  testing/test_terminal.py
Labels: bot:chronographer:provided, backport 8.3.x

#13377 Fix parameter handling of non-static test methods
  changelog/13377.bugfix.rst
  src/_pytest/compat.py
  testing/python/fixtures.py
Labels: bot:chronographer:provided, backport 8.3.x

#13383 [8.3.x] Fix handling of positional-only parameters in test methods (#13377)
  changelog/13377.bugfix.rst
  src/_pytest/compat.py
  testing/python/fixtures.py
Labels: bot:chronographer:provided

#13380 Fix `ExceptionGroup` traceback filtering of pytest internals
  AUTHORS
  changelog/13380.improvement.rst
  src/_pytest/_code/code.py
  testing/code/test_excinfo.py
Labels: bot:chronographer:provided

#13397 Add `Instant` class to conveniently track elapsed and start/end times
  src/_pytest/junitxml.py
  src/_pytest/pytester.py
  src/_pytest/runner.py
  src/_pytest/terminal.py
  src/_pytest/timing.py
  testing/_py/test_local.py
  testing/test_pytester.py
Labels: skip news, bot:chronographer:provided
