Repository pytest-dev/pytest, pull requests merged in 2025-08, with the labels that each got.

#13640 add missing colon
  src/_pytest/raises.py
Labels: type: docs, skip news, backport 8.4.x

#13653 docs(pythonpath): address minor typo
  doc/en/explanation/pythonpath.rst
Labels: skip news

#13665 docs(cacheprovider): add missing docstrings for hooks (pytest_addoption, pytest_configure, cacheshow)
  changelog/13625.doc.rst
  src/_pytest/cacheprovider.py
Labels: bot:chronographer:provided

#13683 fix: change Exeption to Exception in raises.py
  src/_pytest/raises.py
  testing/python/raises_group.py
Labels: skip news, backport 8.4.x
