Repository pytest-dev/pytest, pull requests merged in 2025-05, with the labels that each got.

#13405 doc: Update trainings
  doc/en/index.rst
Labels: skip news, backport 8.3.x

#13404 Add name attribute to testsuites in junitxml
  AUTHORS
  changelog/12736.improvement.rst
  src/_pytest/junitxml.py
  testing/test_junitxml.py
Labels: bot:chronographer:provided

#13416 Willynilly update citation files
  AUTHORS
  CITATION
  changelog/13415.improvement.rst
Labels: bot:chronographer:provided, backport 8.3.x

#13429 Make assertion rewrite warning messages filterable
  changelog/5473.improvement.rst
  src/_pytest/assertion/rewrite.py
  testing/test_assertrewrite.py
Labels: bot:chronographer:provided

#13444 testing: skip `pkg_resources` tests if modern setuptools
  testing/acceptance_test.py
  testing/test_monkeypatch.py
Labels: skip news, backport 8.3.x

#13449 Sunset the mailing list contact information
  CONTRIBUTING.rst
  doc/en/contact.rst
Labels: skip news, backport 8.3.x

#13448 Improvement: #13420 - Update logic of nodes._check_initialpaths_for_relpath
  AUTHORS
  changelog/13420.improvement.rst
  src/_pytest/nodes.py
Labels: bot:chronographer:provided, backport 8.3.x

#13440 officially support python 3.14
  .github/workflows/test.yml
  changelog/13308.improvement.rst
  pyproject.toml
  src/_pytest/pastebin.py
  testing/python/raises.py
  testing/test_debugging.py
  testing/test_parseopt.py
  testing/test_pastebin.py
  testing/test_unraisableexception.py
  tox.ini
Labels: bot:chronographer:provided

#13454 fix GH ci jobs having the wrong name
  .github/workflows/test.yml
Labels: skip news, bot:chronographer:provided

#12934 use Contextmanagers to handle StopIteration in generators
  changelog/12929.bugfix.rst
  src/_pytest/logging.py
  testing/acceptance_test.py
Labels: bot:chronographer:provided
