Repository pytest-dev/pytest, pull requests merged in 2025-10, with the labels that each got.

#13764 Format file patterns
  doc/en/getting-started.rst
Labels: type: docs, skip news, backport 8.4.x

#13780 Change PytestRemovedIn9Warning to error by default
  changelog/13779.breaking.rst
  src/_pytest/deprecated.py
  src/_pytest/warning_types.py
  src/_pytest/warnings.py
  src/pytest/__init__.py
  testing/acceptance_test.py
  testing/test_warnings.py
Labels: bot:chronographer:provided

#13679 Make it possible for faulthandler to terminate the pytest process on timeout
  AUTHORS
  changelog/13678.feature.rst
  doc/en/reference/reference.rst
  src/_pytest/faulthandler.py
  testing/test_faulthandler.py
Labels: bot:chronographer:provided

#13788 Docs/add pytest approx mentions
  doc/en/getting-started.rst
  doc/en/how-to/assert.rst
Labels: skip news

#13791 DEP: bump minimal requirements for iniconfig (1.0.0 -> 1.0.1) and packaging (20.0.0 -> 22.0.0)
  changelog/13791.packaging.rst
  pyproject.toml
Labels: bot:chronographer:provided

#12244 Fixed color test when TERM=dumb
  AUTHORS
  changelog/12244.contrib.rst
  testing/io/test_terminalwriter.py
Labels: bot:chronographer:provided

#13792 Skip symlink sibling test on Windows without symlink support
  AUTHORS
  changelog/13771.contrib.rst
  testing/test_collection.py
Labels: bot:chronographer:provided

#13798 testing: add a test demonstrating why `prune_dependency_tree` is needed
  testing/python/fixtures.py
Labels: skip news
