Repository pytest-dev/pytest, pull requests merged in 2025-07, with the labels that each got.

#13426 Support PEP420 (implicit namespace packages) as `--pyargs` target.
  changelog/478.feature.rst
  doc/en/reference/reference.rst
  src/_pytest/main.py
  testing/test_collection.py
  testing/test_main.py
Labels: bot:chronographer:provided

#13605 doc: Update trainings
  doc/en/index.rst
Labels: type: docs, skip news, backport 8.4.x

#13014 Apply PEP 639
  pyproject.toml
Labels: skip news

#13621 selftests: Set a timeout for lsof
  changelog/13621.contrib.rst
  testing/test_capture.py
Labels: bot:chronographer:provided, backport 8.4.x
