Repository pytest-dev/pytest, pull requests merged in 2025-06, with the labels that each got.

#13472 RELEASING: remove pytest mailing list
  RELEASING.rst
Labels: skip news, backport 8.4.x

#13486 Fix possible typo in docs regarding capteesys
  doc/en/builtin.rst
  src/_pytest/capture.py
Labels: skip news

#13492 Remove outdated warning about faulthandler_timeout on Windows
  changelog/13492.doc.rst
  doc/en/how-to/failures.rst
Labels: type: docs, bot:chronographer:provided, backport 8.4.x

#13525 pytester: avoid unraisableexception gc collects in inline runs to speed up test suite
  src/_pytest/pytester.py
  src/_pytest/unraisableexception.py
  testing/test_config.py
  testing/test_unraisableexception.py
Labels: skip news, backport 8.4.x

#13528 Remove unused code related to `nose`
  src/_pytest/unittest.py
Labels: skip news

#13548 Fix test_doctest_unexpected_exception
  changelog/13547.contrib.rst
  testing/test_doctest.py
Labels: bot:chronographer:provided, backport 8.4.x

#13550 Defer annotation eval on Python 3.14
  changelog/13549.bugfix.rst
  src/_pytest/compat.py
  src/_pytest/fixtures.py
  src/_pytest/nodes.py
  testing/test_collection.py
Labels: bot:chronographer:provided, backport 8.4.x

#13554 Rename 13480.bugfix to 13480.contrib
  changelog/13480.bugfix.rst
  changelog/13480.contrib.rst
Labels: bot:chronographer:provided, backport 8.4.x

#13563 Import numpy conditionally in `pytest.approx`
  AUTHORS
  changelog/13563.bugfix.rst
  src/_pytest/python_api.py
Labels: bot:chronographer:provided, backport 8.4.x

#13445 use callable protocols for pytest.skip/exit/fail/xfail instead of _WithException wrapper with __call__ attribute
  AUTHORS
  changelog/13445.bugfix.rst
  src/_pytest/outcomes.py
  testing/python/collect.py
Labels: bot:chronographer:provided
