Repository pytest-dev/pytest, pull requests merged in 2025-01, with the labels that each got.

#13097 Update LICENSE, fix copyright license year
  LICENSE
Labels: skip news

#13098 Revert "Update LICENSE, fix copyright license year"
  LICENSE
Labels: skip news

#13113 Fix selftests with Pygments >= 2.19.0
  changelog/13112.contrib.rst
  testing/conftest.py
  testing/test_terminal.py
Labels: bot:chronographer:provided, backport 8.3.x

#13086 Fix scandir() crash by returning [] when directory is not found (#13083)
  AUTHORS
  changelog/13083.bugfix.rst
  src/_pytest/pathlib.py
  testing/test_pathlib.py
Labels: bot:chronographer:provided, backport 8.3.x

#13100 Fix `-vv` overriding `--durations-min` (#12938)
  AUTHORS
  changelog/12938.bugfix.rst
  src/_pytest/runner.py
  testing/acceptance_test.py
Labels: bot:chronographer:provided

#13122 Improve stepwise to not forget failed tests
  changelog/13122.improvement.rst
  src/_pytest/stepwise.py
  testing/test_cacheprovider.py
  testing/test_stepwise.py
Labels: bot:chronographer:provided

#13126 Add confval ``console_output_style`` option ``times``
  AUTHORS
  changelog/13125.feature.rst
  doc/en/reference/reference.rst
  src/_pytest/terminal.py
  testing/test_terminal.py
Labels: bot:chronographer:provided

#13152 Fix example in pytest_collection_modifyitems
  src/_pytest/hookspec.py
Labels: skip news, backport 8.3.x

#13153 Fix internal mypy error on Windows
  src/_pytest/_py/error.py
Labels: skip news, backport 8.3.x

#13134 Accept generic ExceptionGroups for raises
  AUTHORS
  changelog/13115.improvement.rst
  src/_pytest/python_api.py
  testing/code/test_excinfo.py
Labels: bot:chronographer:provided

#13061 Add --force-short-summary option and extend sequence printing with -vv
  changelog/11777.bugfix.rst
  changelog/12713.feature.rst
  src/_pytest/assertion/rewrite.py
  src/_pytest/terminal.py
  testing/test_terminal.py
Labels: bot:chronographer:provided

#13163 [8.3.x] Fix sequences being shortened even with `-vv` verbosity.
  changelog/11777.bugfix.rst
  src/_pytest/assertion/rewrite.py
  testing/test_terminal.py
Labels: bot:chronographer:provided

#13102 Add basic implementation of PEP657 style expression markers in tracebacks
  AUTHORS
  changelog/10224.improvement.rst
  src/_pytest/_code/code.py
  src/_pytest/_code/source.py
  testing/code/test_excinfo.py
Labels: bot:chronographer:provided
